### PR TITLE
The orientation flag is not passed on puppeteer. Proposed fix.

### PR DESCRIPTION
**Pull request by csingewald**

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
Hey, thanks for this. I'm away from my computer for the weekend but from what I can see on my phone this looks good. I'll merge it once I get back 😄

**Comment by BlueHatbRit** [comment]
I tweaked the commit and merged it to master with you as the author here: https://github.com/BlueHatbRit/mdpdf/commit/7778323d2993d296aadfe01021b2a3ec1b133c93 before I push it out. Right now it's set to `christoph@Selma.local` as you haven't set a git email address locally, this means github won't link it through to your github profile.

Do you want me to edit the email address before I publish it? If so, what email are you using on yout github account?

Thanks again for the contribution!

**Comment by csingewald** [comment]
﻿Hi,

yes you are right, I did not set my email address locally.
Here is the email I use on github: christoph@singewald.at.
Thank you for pointing out and editing .

Best regards,
Christoph

Dipl.-Ing. Christoph Singewald
Inhaber,Leiter Entwicklung

Chenos e.U.
eingetragenes Einzelunternehmen, Inhaber: Dipl.-Ing. Christoph Singewald
FN 367789 t; FB-Gericht: Landessericht St.Pölten
Steinriegl 2
3451 Michelhausen
Tel.: +43 (0) 699 11452459
E-Mail christoph.singewald@chenos.com

**Comment by BlueHatbRit** [comment]
That's fixed for you and is showing up in the commit log properly. Thanks for your contribution Christoph! 🚀 i'll do a release sometime today

**Pull request closed without merging**
