### PR TITLE
Load global css configuration

### PR DESCRIPTION
**Pull request by nwtgck**
Thank you for your wonderful project!

The `--style` option is great, but I'd like to load a global CSS setting. So I changed `mdpdf` to load `$HOME/config/mdpdf/style.css` if it exists.

### CODE REVIEW

**Comment by nwtgck** [comment]
In my environment, both node 4.8.7 and 7.10.1 had passed all tests. In addition, my build in Travis has also passed https://travis-ci.org/nwtgck/mdpdf.

**Comment by BlueHatbRit** [comment]
Hi @nwtgck, thanks for the encouragement and for the PR! Don't worry about the tests, if you take a look it's actually just timeout issues because these tests take an age to run, I've been meaning to up the timeout setting on mocha and will do it asap. I tend to run tests locally before merging anyway so it's all good.

The concept of this intrigues me, I've not had a chance to take a proper look at the code yet but it looks like a great idea.

My one thought is that we probably shouldn't force a location for the css file, I'm wondering whether it'd be better for us to introduce an environment variable instead? That way you can put the file wherever you like, and just need to set the environment variable to point to that file. This might work nicer with version controller dotfiles for example.

What do you think? As the one who's found the need for this and written the code so I'd love your thoughts!

**Comment by BlueHatbRit** [comment]
You can ignore the idea of dotfiles, they're not important at all! All it means is that instead of looking for the specific file as you have, you'll instead look to see if `process.env.MDPDF_STYLES` is set, and if it is then you'll use that as the style path. Basically the same as you've got here already!

Is that something you'd like to do in your PR?

**Comment by nwtgck** [comment]
I changed mdpdf to use $MDPDF_STYLES to specify global CSS path!

**Comment by BlueHatbRit** [comment]
Hi @nwtgck, thanks for the update! I'll take a pull of this and give it a once over sometime today or tomorrow and get it in ASAP! No one likes to be waiting for a PR to be merged ;)

**Comment by BlueHatbRit** [comment]
Hey there @nwtgck, thanks so much for the code! I made one small change to the branch which was moving it out of the main index.js and into the bin/index.js file.

`bin/index.js` is the entry point for the CLI (when you call `mdpdf --styles=...` etc), where as the `index.js` file in the root is the main "lib" as I tend to call it. This root file can actually be used as a nodejs module by someone if they pull it into their project! (An atom extension uses this for example).

So I've moved it into the CLI code (which then calls the main lib code) so that it won't be in use if someone is trying to use it through JavaScript directly. This should just reduce the impact of the change on people.

Would you mind looking at it and seeing what you think? It's your code after all :) I made the commit to your branch on your repo since [you granted me access to add to this PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) so you should be able to just pull your master branch of your fork again.

**Comment by nwtgck** [comment]
Thank you for giving the review! You allowed both CLI users and library users benefit from `$MDPDF_STYLES`. I think this is great idea!

I've reviewed code, used `mdpdf` as command and confirmed it worked pretty well.

**Comment by BlueHatbRit** [comment]
Great, I'll get this merged now and release it sometime today.

Just to clarify, it is only CLI users that benefit from the `MDPDF_STYLES` environment variable, not library users, but I think this is better as they can choose to implement the environment variable themselves.

Thanks for the contribution @nwtgck!

**Comment by nwtgck** [comment]
> Just to clarify, it is only CLI users that benefit from the MDPDF_STYLES environment variable, not library users, but I think this is better as they can choose to implement the environment variable themselves.

I misunderstood. My change had affected library users, so you revised it not to surprise them.  This is very user-friendly!

**Comment by nwtgck** [comment]
I just remember my addition to `README.md`. So I removed the section from it.

**Comment by BlueHatbRit** [comment]
Released as part of 1.6.0 https://github.com/BlueHatbRit/mdpdf/releases/tag/1.6.0

**Pull request merged**
