### PR TITLE
Support syntax highlighting via showdown-higlight

### PR DESCRIPTION
**Pull request by ncpenke**

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
Hey @ncpenke, thanks so much for this! I've just gone through and ripped out the existing highlight implementation we're using and suddenly code highlights stopped working when I was just using this code. Any idea why this might be? I'm using the readme in this repo as my test case but it's coming out without any highlighting.

It's working fine when I re-include the original implementation but I imagine this is probably because of our legacy implementation which this is designed to replace.

Any ideas?

**Comment by BlueHatbRit** [comment]
Oops my mistake, I assumed the showdown plugin came bundled with the stylesheets which is not the case. We still need to provide the stylesheet, the plugin will simply apply the appropriate html tags. I'll continue testing this then!

**Comment by BlueHatbRit** [comment]
I've merged this onto the master and added a couple extra commits, I also edited the commit to include the package-lock.json which didn't quiet seem to be up to date so that's why github hasn't recognised it on this PR. None the less it's in the master branch here - https://github.com/BlueHatbRit/mdpdf/commit/ef6dee4a31276ccc0aef4b00a937d8125ec8a758

I've tagged 2.1.2, I'm just going to run through a few more test scenarios before I publish it to npm. 🎊 i'll close this now it's been merged and will post here again when the release has been pushed.

**Comment by BlueHatbRit** [comment]
2.1.2 has hit npm now, thanks again!

**Comment by ncpenke** [comment]
Glad you were able to figure out the stylesheet issue. Thanks for integrating this so quickly!

**Pull request closed without merging**
