### PR TITLE
Add loophole wrapper for template function

### PR DESCRIPTION
**Pull request by travs**
- add loophole dependency

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
Just a note, if the tests fail it's most likely phantomjs being slow as a slug, I'll run the tests locally if that happens and force the merge.

**Comment by travs** [comment]
@BlueHatbRit 
Ok, I also ran the linter and tests locally and they passed, but you check as well just to be sure!

I found out that my issue with the humongous PDF output was actually due to my not setting the `ghStyle` and `defaultStyle` parameters (I wrongly assumed that they defaulted to `true`).

Do you think we can reword the language [here](https://github.com/BlueHatbRit/mdpdf#options-1) for those two params, since it says "set to false to turn off". To me that means that the default is "true".

In any case, you've been more than helpful in getting this integrated.
I still have a few things to change in the atom project, but I think it is safe to say it will be switching to your converter as default as soon as `mdpdf` has a  new version.
Will change docs, etc to give appropriate credit.

**Comment by BlueHatbRit** [comment]
@travs I totally agree, I think I might have made a change and missed that piece of documentation but I'll get it sorted.

I'm just going to run a quick test of your branch locally through the CLI to make sure everything's still outputting correctly. Once that's done I'll get this merged and ship the next version. I'll give you a ping on the other issue once it's done.

I'm all for getting mdpdf into your extension, I wrote it originally because I liked your module but wanted to be editor agnostic and get some automation going on. Getting this into your module would be a great way of contributing back.

**Comment by travs** [comment]
@BlueHatbRit 
Perfect.
Hah yes, I liked your blog post about that actually, and it's awesome that it has kind of come full circle.
The magic of open source I suppose.

**Comment by BlueHatbRit** [comment]
@travs glad you liked the post, I hope it wasn't too critical! The magic indeed, I think it's time I brushed up on my coffee script to get my hands dirty with your plugin now.

I've run a few tests with some awkward markdown files and everything looks great. I'm merging this now and I'll ping the other issue on your repo once the release has been made.

**Comment by BlueHatbRit** [comment]
For archival purposes, I've made a documentation change to the readme which will go out with the next release. This change clarifies the defaults of some of the options through the JS API.

**Pull request merged**
