### PR TITLE
Replace emoji codes with images

### PR DESCRIPTION
**Pull request by stoe**
Add capability to replace emoji codes e.g. `:+1:` with images :+1: using the showdown plugin https://www.npmjs.com/package/showdown-emoji

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
Hi @stoe, thanks for the pull request! I'm just checking it runs on my machine as well and then hopefully we can get this merged!

**Comment by BlueHatbRit** [comment]
@stoe, Did you test `:+1:` specifically? When I run a file through I can only seem to get it to work using the long hand version such as `:thumbsup:`. However I've given a large number of emojis a bash and it seems to work fine excluding those short hand versions. Assuming there isn't some weird discrepancy, I'm happy to merge this in!

**Comment by stoe** [comment]
Thanks for the catch @BlueHatbRit.

I think the short hand alias support is missing in https://www.npmjs.com/package/showdown-emoji.
Unfortunately https://github.com/IonicaBizau/showdown-emoji is a private repo, otherwise I would create a PR to add the aliases there.

If you think it's :ok: to merge still, please feel free to do so.

Alternatively I can add a description to the `README` describing the known issue with the emoji shorthands.

**Comment by BlueHatbRit** [comment]
I just wanted to make sure this wasn't something that was only happening on my machine for some reason. I'm happy to merge without the shorthand versions! It's a shame that repo is private though, but the package works well for now.

**Comment by BlueHatbRit** [comment]
The release has been made, though I did mess it up by using Yarn by habit, so we're now bumped to 1.1.1 and all is well. Thanks for the contribution @stoe!

**Comment by stoe** [comment]
> I did mess it up by using Yarn by habit, so we're now bumped to 1.1.1

Frequently happens to me, too

**Pull request merged**
